[project]
name = "workspace"
version = "0.8.0"
description = "Django workspace project"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django>=6.0.2,<7.0",
    "djangorestframework==3.16.1",
    "django-filter==25.2",
    "drf-spectacular==0.29.0",
    "drf-orjson-renderer>=1.7.0",
    "whitenoise>=6.11.0",
    "django-redis>=5.4.0",
    "django-simple-history>=3.8.0",
    "django-daisy>=2.0.5",
    # celery
    "celery>=5.6.2",
    "redis>=7.1.0",
    # imaging
    "pillow>=11.0",
    "cairosvg>=2.7.0",
    # mail
    "cryptography>=44.0.0",
    "nh3>=0.2.20",
    "myl-discovery>=0.6.4",
    "icalendar>=6.1.0",
    # utils
    "mistune>=3.2.0",
    "dj-database-url>=2.3.0",
    "psycopg[binary,pool]>=3.2.0",
    # webdav
    "wsgidav>=4.3.0",
    # server
    "gunicorn>=24.1.1",
    "django-brotli>=0.4.0",
    "gevent>=25.9.1",
    "django-prometheus>=2.4.0",
    # push notifications
    "pywebpush>=2.3.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "django-debug-toolbar==6.2.0",
]
